workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    working_directory: ~/articleList
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest . --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME
      - run:
          name: run-docker-image
          command: docker run -p 3000:3000 -d $IMAGE_NAME
deploy:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - run:
          name: deploy-application
          command: |
            ssh -i <path_to_private_key> ubuntu@ec2-13-49-231-69.eu-north-1.compute.amazonaws.com \
            "sudo docker pull $IMAGE_NAME && \
            sudo docker stop $CONTAINER_NAME && sudo docker rm $CONTAINER_NAME && \
            sudo docker run -p 3000:3000 -d --name $CONTAINER_NAME $IMAGE_NAME"
